#!/usr/bin/bash

# logo AA定義
LOGO="logo"

while true;do
  clear
  echo -e "\e[33;40m研究室見学大歓迎！\nただいま対応者昼食中  約１時間後またお越しください\e[0;40m"
  sleep 1 
  while read LINE;do
    echo $LINE
    sleep 0.4
  done < ${LOGO}
  sleep 3
done
